# Generated by Django 4.1.3 on 2022-11-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0002_posts_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
